name: Build & push EstacionaTEC images to GHCR

on:
  push:
    branches: ["main"]

permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & push frontend
        uses: docker/build-push-action@v6
        with:
          context: ./Frontend
          file: ./Frontend/Dockerfile
          push: true
          tags: |
            ghcr.io/johancamachodevsec/estacionatec-frontend:latest

      - name: Build & push backend
        uses: docker/build-push-action@v6
        with:
          context: ./BackEnd/APIS
          file: ./BackEnd/APIS/Dockerfile
          push: true
          tags: |
            ghcr.io/johancamachodevsec/estacionatec-backend:latest
